swagger: "2.0"

info:
  title: Example Microservice
  description: This is the API to obtain patient information from inside the Medical Center
  version: "1.0"
schemes:
  - http
basePath:  /v1.0
consumes:
  - application/json
produces:
  - application/json
paths:
  /patient/{id}:
    parameters:
      - name: id
        in: path
        description: Patient id must be unique along all the application
        required: true
        type: string
    get:
      tags:
        - "Patient"
      summary: "Get a report of the information available from a patient {id}"
      responses:
        '200':
          description: 'The report should have relevant information about patient'
          schema:
            type: array
            items:
              $ref: '#/definitions/Report'
  /patients/:
    get:
      tags:
        - "Patients"
      summary: "Get all available patients"
      responses:
        '200':
          description: 'List of all available patients'
          schema:
            type: array
            items:
              $ref: '#/definitions/Patient'
definitions:
  Report:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      image:
        type: string
  Patient:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
