swagger: "2.0"

info:
  title: Example Microservice
  version: "1.0"
schemes:
  - http
basePath:  /v1.0
consumes:
  - application/json
produces:
  - application/json
paths:
  /items/:
    get:
      responses:
        '200':
          description: 'Fetch list of available items'
          schema:
              type: array
              items:
                $ref: '#/definitions/Item'
definitions:
  Item:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: {type: string}
